name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: xmly_speed
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: '运行 【喜马拉雅极速版】'
        run: python3 xmly_speed.py
        env:
          XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
          BARK: ${{ secrets.BARK }}     # bark服务
          SCKEY: ${{ secrets.SCKEY }}   # server酱服务
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
          TG_USER_ID: ${{secrets.TG_USER_ID}}    # tg通知id
